# Generated by Django 4.1.1 on 2025-10-14 07:15

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sp_asset_name', models.CharField(max_length=255, verbose_name='Secret Party Asset Name')),
                ('hotel_room_type_code', models.CharField(max_length=20, verbose_name='Hotel Room Type Code')),
                ('hotel_name', models.CharField(choices=[("Bally's", 'Ballys'), ('Nugget', 'Nugget')], max_length=20, verbose_name='Hotel Name')),
                ('hotel_room_type_name', models.CharField(max_length=255, verbose_name='Hotel Room Type Name')),
            ],
            options={
                'unique_together': {('sp_asset_name', 'hotel_room_type_code')},
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
