#!/usr/bin/env bash

set -e

SCRIPTDIR=$( cd "${0%/*}" && pwd)
ROOTDIR="${SCRIPTDIR%/*}"

if docker compose ps | grep -q backend ; then
    docker compose run \
	   -v "${ROOTDIR}:${ROOTDIR}" \
	   --rm \
	   backend \
	   uv run /usr/src/app/manage.py "$@"
else
    if [ -n "$ROOMBAHT_CONFIG" ] ; then
	echo "Using alternative config ${ROOMBAHT_CONFIG}"
	if [ ! -e "$ROOMBAHT_CONFIG" ] ; then
	    echo "Unable to open alternate config, lollll"
	    exit 2
	fi
    else
	ROOMBAHT_CONFIG="${ROOTDIR}/dev.env"
    fi
    source "$ROOMBAHT_CONFIG"
    uv run \
       --python "$(cat "${ROOTDIR}/.python-version")" \
       --project "${ROOTDIR}/backend/pyproject.toml" \
       "${ROOTDIR}/backend/manage.py" "$@"
fi
